/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string | null;
export type Date = string;
export type Medialist = string[];
export type Id1 = string | null;
export type Name = string;
export type Address = string | null;
export type Phonenumber = string | null;
export type Photoofperson = string;
export type Resumephotoslist = string[];
export type Biodataphotoslist = string[];
export type Email = string | null;
export type Datejoined = string;
export type Company = string;
export type Isregular = boolean;
export type Isproductionemployee = boolean;
export type Dailywage = number | null;
export type Version = number;
export type Memophotoslist = string[];
export type Subject = string;
export type Description = string;
export type Id2 = string | null;
export type Number = number;
export type Description1 = string;
export type Remedialactions = string[];
export type Version1 = number;
export type Submitted = boolean;
export type Reason = string | null;
export type Version2 = number;

export interface Memo {
  _id?: Id;
  date: Date;
  mediaList: Medialist;
  Employee: Employee;
  memoPhotosList: Memophotoslist;
  subject: Subject;
  description: Description;
  MemoCode: Offense;
  submitted: Submitted;
  reason: Reason;
  _version: Version2;
}
export interface Employee {
  _id?: Id1;
  name: Name;
  address: Address;
  phoneNumber: Phonenumber;
  photoOfPerson: Photoofperson;
  resumePhotosList: Resumephotoslist;
  biodataPhotosList: Biodataphotoslist;
  email: Email;
  dateJoined: Datejoined;
  company: Company;
  isRegular: Isregular;
  isProductionEmployee: Isproductionemployee;
  dailyWage: Dailywage;
  _version: Version;
  [k: string]: unknown;
}
export interface Offense {
  _id?: Id2;
  number: Number;
  description: Description1;
  remedialActions: Remedialactions;
  _version: Version1;
  [k: string]: unknown;
}
