 
import type { Metadata } from "next";

import "./globals.css";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

import NavBar from "./NavigationComponents/NavBar"; 

import ContextProvider from "./GlobalContext/index";

export const metadata: Metadata = {
  title: "Employee Profile Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.variable} overflow-x-clip antialiased`}> 
        <ContextProvider>
          {children} 
          <NavBar /> 
        </ContextProvider> 
      </body>
    </html>
  );
}
